package userfrom;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Abdul Karim
 */
public class Login extends javax.swing.JFrame {
    Connection conn = null;
    public Login() {
        conn = Connect.ConnectDB();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        usertxt = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        passwordtxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSingup = new javax.swing.JButton();
        combo_login = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        wrongPanel = new javax.swing.JPanel();
        wrongMessage = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(500, 70, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 2, 14), new java.awt.Color(0, 0, 153)), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 255)))); // NOI18N
        jPanel1.setLayout(null);
        jPanel1.add(usertxt);
        usertxt.setBounds(186, 122, 145, 29);

        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        btnlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnloginKeyPressed(evt);
            }
        });
        jPanel1.add(btnlogin);
        btnlogin.setBounds(241, 256, 90, 30);
        jPanel1.add(passwordtxt);
        passwordtxt.setBounds(181, 177, 150, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("UserName:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(65, 121, 109, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(65, 178, 104, 30);

        btnSingup.setText("SignUp");
        btnSingup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingupActionPerformed(evt);
            }
        });
        btnSingup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSingupKeyPressed(evt);
            }
        });
        jPanel1.add(btnSingup);
        btnSingup.setBounds(241, 304, 90, 25);

        combo_login.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Techer" }));
        jPanel1.add(combo_login);
        combo_login.setBounds(181, 226, 150, 24);

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Role");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(65, 231, 51, 15);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.red);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Forget Password?");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 270, 110, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userfrom/sdn-programing-api.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 30, 400, 310);

        wrongPanel.setBackground(new java.awt.Color(204, 204, 255));
        wrongPanel.setLayout(null);

        wrongMessage.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        wrongMessage.setForeground(new java.awt.Color(0, 0, 255));
        wrongMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wrongPanel.add(wrongMessage);
        wrongMessage.setBounds(0, 0, 441, 28);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(wrongPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(wrongPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed

       
       userid = usertxt.getText();
       password = passwordtxt.getText();
       String value=combo_login.getSelectedItem().toString();
       
       int check=0;
       if(userid.isEmpty())
       {
           check=1;
           //JOptionPane.showMessageDialog(null,"UserName field is empty");
           wrongPanel.setBackground(new java.awt.Color(255, 0, 0));
           wrongMessage.setText("User Name field is empty");
           passwordtxt.setText(s);
       }
       else if(password.isEmpty())
       {
           check=1;
           //JOptionPane.showMessageDialog(null,"Password field empty");
           wrongPanel.setBackground(new java.awt.Color(255, 0, 0));
           wrongMessage.setText("Password field is empty");
       }
       if(check==0 && value.equals("Administrator")){
            try {
                String sql =new String();
                    sql="select * from UserInfo";
                ps = conn.prepareStatement(sql);
                rs = ps.executeQuery();
                int flage = 0;
                while(rs.next()){
                    if(rs.getString("usename").equals(userid) && rs.getString("password").equals(password)){
                        flage = 1;
                            Main n = new Main(conn);
                            n.details(rs.getString("name"),userid);
                            rs.close();
                            ps.close();
                            n.setVisible(true);
                            this.setVisible(false);
                        
                    }

                }
                if(flage==0){
                    //usertxt.setText(s);
                    passwordtxt.setText(s);
                    //JOptionPane.showMessageDialog(null, "InCorrect Login Credentials");
                    wrongPanel.setBackground(new java.awt.Color(255, 0, 0));
                    wrongMessage.setText("User Name or Password is incorrect");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    rs.close();
                    ps.close();
                } catch (SQLException ex) {
                    wrongPanel.setBackground(new java.awt.Color(255, 0, 0));
                    wrongMessage.setText("Data closing Problem try Again");
                }
            }
       }else if(check==0 && value.equals("Techer")){
           try {
                userid = usertxt.getText();
                password = passwordtxt.getText();
                ps = conn.prepareStatement("select * from techertb");
                rs = ps.executeQuery();
                int flage = 0;
                while(rs.next()){
                    if(rs.getString("usename").equals(userid) && rs.getString("password").equals(password)){
                        flage=1;
                        Techerpage p = new Techerpage();
                        p.details(rs.getString("name"),userid);
                        //p.imagedata();
                        rs.close();
                        ps.close();
                        p.setVisible(true);
                        this.setVisible(false);
                    }

                }
                if(flage==0){
                    //usertxt.setText(s);
                    passwordtxt.setText(s);
                    //JOptionPane.showMessageDialog(null, "InCorrect Login Credentials");
                    wrongPanel.setBackground(new java.awt.Color(255, 0, 0));
                    wrongMessage.setText("User Name or Password is incorrect");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    rs.close();
                    ps.close();
                } catch (SQLException ex) {
                    wrongPanel.setBackground(new java.awt.Color(255, 0, 0));
                    wrongMessage.setText("Data closing Problem try Again");
                }
            }
       }

    }//GEN-LAST:event_btnloginActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //conn = Connect.ConnectDB();
    }//GEN-LAST:event_formWindowOpened

    private void btnSingupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingupActionPerformed
        this.setVisible(false);
        Registration s=new Registration(conn);
        s.setVisible(true);
    }//GEN-LAST:event_btnSingupActionPerformed

    private void btnloginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnloginKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            userid = usertxt.getText();
            password = passwordtxt.getText();
            String value=combo_login.getSelectedItem().toString();

            int check=0;
            if(userid.isEmpty())
            {
                check=1;
                //JOptionPane.showMessageDialog(null,"UserName field is empty");
                wrongPanel.setBackground(new java.awt.Color(255, 0, 0));
                wrongMessage.setText("User Name field is empty");
                passwordtxt.setText(s);
            }
            else if(password.isEmpty())
            {
                check=1;
                //JOptionPane.showMessageDialog(null,"Password field empty");
                wrongPanel.setBackground(new java.awt.Color(255, 0, 0));
                wrongMessage.setText("Password field is empty");
            }
            if(check==0 && value.equals("Administrator")){
                 try {
                     String sql =new String();
                         sql="select * from UserInfo";
                     ps = conn.prepareStatement(sql);
                     rs = ps.executeQuery();
                     int flage = 0;
                     while(rs.next()){
                         if(rs.getString("usename").equals(userid) && rs.getString("password").equals(password)){
                             flage = 1;
                                 Main n = new Main(conn);
                                 n.details(rs.getString("name"),userid);
                                 rs.close();
                                 ps.close();
                                 n.setVisible(true);
                                 this.setVisible(false);

                         }

                     }
                     if(flage==0){
                         //usertxt.setText(s);
                         passwordtxt.setText(s);
                         //JOptionPane.showMessageDialog(null, "InCorrect Login Credentials");
                         wrongPanel.setBackground(new java.awt.Color(255, 0, 0));
                         wrongMessage.setText("User Name or Password is incorrect");
                     }
                 } catch (SQLException ex) {
                     Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                 }finally{
                     try {
                         rs.close();
                         ps.close();
                     } catch (SQLException ex) {
                         wrongPanel.setBackground(new java.awt.Color(255, 0, 0));
                         wrongMessage.setText("Data closing Problem try Again");
                     }
                 }
            }else if(check==0 && value.equals("Techer")){
                try {
                     userid = usertxt.getText();
                     password = passwordtxt.getText();
                     ps = conn.prepareStatement("select * from techertb");
                     rs = ps.executeQuery();
                     int flage = 0;
                     while(rs.next()){
                         if(rs.getString("usename").equals(userid) && rs.getString("password").equals(password)){
                             flage=1;
                             Techerpage p = new Techerpage();
                             p.details(rs.getString("name"),userid);
                             //p.imagedata();
                             rs.close();
                             ps.close();
                             p.setVisible(true);
                             this.setVisible(false);
                         }

                     }
                     if(flage==0){
                         //usertxt.setText(s);
                         passwordtxt.setText(s);
                         //JOptionPane.showMessageDialog(null, "InCorrect Login Credentials");
                         wrongPanel.setBackground(new java.awt.Color(255, 0, 0));
                         wrongMessage.setText("User Name or Password is incorrect");
                     }
                 } catch (SQLException ex) {
                     Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                 }finally{
                     try {
                         rs.close();
                         ps.close();
                     } catch (SQLException ex) {
                         wrongPanel.setBackground(new java.awt.Color(255, 0, 0));
                         wrongMessage.setText("Data closing Problem try Again");
                     }
                 }
            }
        }
    }//GEN-LAST:event_btnloginKeyPressed

    private void btnSingupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSingupKeyPressed
        this.setVisible(false);
        Registration s=new Registration(conn);
        s.setVisible(true);
    }//GEN-LAST:event_btnSingupKeyPressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setVisible(false);
        new Forget(conn).setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked
    ResultSet rs=null;
    PreparedStatement ps=null;
    String userid=new String();
    String password = new String();
    String s=new String();
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSingup;
    private javax.swing.JButton btnlogin;
    private javax.swing.JComboBox<String> combo_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JTextField usertxt;
    private javax.swing.JLabel wrongMessage;
    private javax.swing.JPanel wrongPanel;
    // End of variables declaration//GEN-END:variables
}
