
package userfrom;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Abdul Karim
 */
public class RoutineFrom extends javax.swing.JFrame {

    Connection conn=null;
    public RoutineFrom(Connection conn) {
        this.conn=conn;
        initComponents();
        list1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        combo_Roomlist = new javax.swing.JComboBox<>();
        comboTecherlist = new javax.swing.JComboBox<>();
        show = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roution From");
        setBounds(new java.awt.Rectangle(400, 70, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(2);
        jTable1.setRowSelectionAllowed(false);
        jTable1.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Room");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Teacher");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnReset.setText("Reset Routine");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userfrom/Go-back-icon (1).png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        combo_Roomlist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "............" }));
        combo_Roomlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_RoomlistActionPerformed(evt);
            }
        });

        comboTecherlist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..............." }));
        comboTecherlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTecherlistActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Time:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("8:00-9:20");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("9:20-10:50");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("11:00-12:20");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("12:30-1:50");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("2:00-3:20");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("3:30-4:50");

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1-1", "1-2", "2-1", "2-2", "3-1", "3-2", "4-1", "4-2" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(205, 205, 205)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(combo_Roomlist, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTecherlist, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnPrint)
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btnReset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(19, 19, 19)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(combo_Roomlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTecherlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrint)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String room[]=new String[100];
        String user[]=new String[100];
        int i=-1,j=-1;
        
        /*room taken condition*/
        try {
            String sql = "select * from roomlist";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
           while(rs.next())
           {
               i++;
              room[i]=rs.getString("roomno");
                
            }
        } catch (SQLException ex) {
            System.out.println("room get problem");
        }finally{
            try {
                ps.close();
                rs.close();
            } catch (SQLException ex) {
                
                //succesMessage.setText("Closing problem");
            }
        }
        
        /*user taken condition*/
        try {
            String sql = "select * from subchoice";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
           while(rs.next())
           {
               j++;
              user[j]=rs.getString("usename");
                
            }
        } catch (SQLException ex) {
            System.out.println("user get problem");
        }finally{
            try {
                ps.close();
                rs.close();
            } catch (SQLException ex) {
                
                //succesMessage.setText("Closing problem");
            }
        }
        
        
        
        for(int k=0;k<=j;k++){//user check
            String sub[]=new String[10];
            int temp=-1;
            
            try {
            String sql = "select * from subchoice where usename='"+user[k]+"'";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
                if(rs.getString("c1").length()>1){
                    temp++;
                    sub[temp]=rs.getString("c1");
                }
                if(rs.getString("c2").length()>1){
                    temp++;
                    sub[temp]=rs.getString("c2");
                }
                if(rs.getString("c3").length()>1){
                    temp++;
                    sub[temp]=rs.getString("c3");
                }
                if(rs.getString("c4").length()>1){
                    temp++;
                    sub[temp]=rs.getString("c4");
                }
                if(rs.getString("c5").length()>1){
                    temp++;
                    sub[temp]=rs.getString("c5"); 
                }
            } catch (SQLException ex) {
                System.out.println("choice get problem");
            }finally{
                try {
                    ps.close();
                    rs.close();
                } catch (SQLException ex) {

                    //succesMessage.setText("Closing problem");
                }
            }
            if(temp !=-1){
                int aa1=0,aa2=0,aa3=0,aa4=0,aa5=0,aa6=0,bb1=0,bb2=0,bb3=0,bb4=0,bb5=0,bb6=0,
                    cc1=0,cc2=0,cc3=0,cc4=0,cc5=0,cc6=0,dd1=0,dd2=0,dd3=0,dd4=0,dd5=0,dd6=0,
                    ee1=0,ee2=0,ee3=0,ee4=0,ee5=0,ee6=0;
            for(int f=0;f<=temp;f++){///temp is sub index
                //System.out.println(sub[f]);
                int x=0,y=0;
                    for(int kk=0;kk<=i && y==0;kk++){// i is room index
                        
                        String a1=new String();
                        String a2=new String();
                        String a3=new String();
                        String a4=new String();
                        String a5=new String();
                        String a6=new String();
                        String b1=new String();
                        String b2=new String();
                        String b3=new String();
                        String b4=new String();
                        String b5=new String();
                        String b6=new String();
                        String c1=new String();
                        String c2=new String();
                        String c3=new String();
                        String c4=new String();
                        String c5=new String();
                        String c6=new String();
                        String d1=new String();
                        String d2=new String();
                        String d3=new String();
                        String d4=new String();
                        String d5=new String();
                        String d6=new String();
                        String e1=new String();
                        String e2=new String();
                        String e3=new String();
                        String e4=new String();
                        String e5=new String();
                        String e6=new String();
                        
                        try{

                            String sq="select * from '"+room[kk]+"'";
                            ps=conn.prepareStatement(sq);
                            rs=ps.executeQuery();
                            while(rs.next()){ 
                                if(rs.getString("Day").equals("sunday")){
                                    a1=rs.getString("p1");
                                    a2=rs.getString("p2");
                                    a3=rs.getString("p3");
                                    a4=rs.getString("p4");
                                    a5=rs.getString("p5");
                                    a6=rs.getString("p6");
                                }
                                if(rs.getString("Day").equals("monday")){
                                    b1=rs.getString("p1");
                                    b2=rs.getString("p2");
                                    b3=rs.getString("p3");
                                    b4=rs.getString("p4");
                                    b5=rs.getString("p5");
                                    b6=rs.getString("p6");
                                }
                                if(rs.getString("Day").equals("tuesday")){
                                    c1=rs.getString("p1");
                                    c2=rs.getString("p2");
                                    c3=rs.getString("p3");
                                    c4=rs.getString("p4");
                                    c5=rs.getString("p5");
                                    c6=rs.getString("p6");
                                }
                                if(rs.getString("Day").equals("wednesday")){
                                    d1=rs.getString("p1");
                                    d2=rs.getString("p2");
                                    d3=rs.getString("p3");
                                    d4=rs.getString("p4");
                                    d5=rs.getString("p5");
                                    d6=rs.getString("p6");
                                }
                                if(rs.getString("Day").equals("thusday")){
                                    e1=rs.getString("p1");
                                    e2=rs.getString("p2");
                                    e3=rs.getString("p3");
                                    e4=rs.getString("p4");
                                    e5=rs.getString("p5");
                                    e6=rs.getString("p6");
                                }
                            }
                            
                            x=1;
                        }catch(Exception e){
                            System.out.println("room check problem");
                        }
                        
                        /*subject and user insert*/
                        if(x==1){
                            
                            String sq=new String();
                            String g="sunday";
                            String g2="monday";
                            String g3="tuesday";
                            String g4="wednesday";
                            String g5="thusday";
                            if(a3.equals("0") && aa3==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p3='"+sub[f]+" "+user[k]+"' where Day='"+g+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;aa3=1;
                                    troution(g,user[k],sub[f],room[kk],3);
                                    semister(sub[f],g,"p3",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(a4.equals("0") && aa4==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p4='"+sub[f]+" "+user[k]+"' where Day='"+g+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;aa4=1;
                                    troution(g,user[k],sub[f],room[kk],4);
                                    semister(sub[f],g,"p4",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(b3.equals("0") && bb3==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p3='"+sub[f]+" "+user[k]+"' where Day='"+g2+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;bb3=1;
                                    troution(g2,user[k],sub[f],room[kk],3);
                                    semister(sub[f],g2,"p3",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(b4.equals("0") && bb4==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p4='"+sub[f]+" "+user[k]+"' where Day='"+g2+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;bb4=1;
                                    troution(g2,user[k],sub[f],room[kk],4);
                                    semister(sub[f],g2,"p4",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(c3.equals("0") && cc3==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p3='"+sub[f]+" "+user[k]+"' where Day='"+g3+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;cc3=1;
                                    troution(g3,user[k],sub[f],room[kk],3);
                                    semister(sub[f],g3,"p3",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(c4.equals("0") && cc4==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p4='"+sub[f]+" "+user[k]+"' where Day='"+g3+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;cc4=1;
                                    troution(g3,user[k],sub[f],room[kk],4);
                                    semister(sub[f],g3,"p4",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(d3.equals("0") && dd3==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p3='"+sub[f]+" "+user[k]+"' where Day='"+g4+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;dd3=1;
                                    troution(g4,user[k],sub[f],room[kk],3);
                                    semister(sub[f],g4,"p3",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(d4.equals("0") && dd4==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p4='"+sub[f]+" "+user[k]+"' where Day='"+g4+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;dd4=1;
                                    troution(g4,user[k],sub[f],room[kk],4);
                                    semister(sub[f],g4,"p4",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(e3.equals("0") && ee3==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p3='"+sub[f]+" "+user[k]+"' where Day='"+g5+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;ee3=1;
                                    troution(g5,user[k],sub[f],room[kk],3);
                                    semister(sub[f],g5,"p3",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(e4.equals("0") && ee4==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p4='"+sub[f]+" "+user[k]+"' where Day='"+g5+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;ee4=1;
                                    troution(g5,user[k],sub[f],room[kk],4);
                                    semister(sub[f],g5,"p4",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(a5.equals("0") && aa5==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p5='"+sub[f]+" "+user[k]+"' where Day='"+g+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;aa5=1;
                                    troution(g,user[k],sub[f],room[kk],5);
                                    semister(sub[f],g,"p5",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(a6.equals("0") && aa6==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p6='"+sub[f]+" "+user[k]+"' where Day='"+g+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;aa6=1;
                                    troution(g,user[k],sub[f],room[kk],6);
                                    semister(sub[f],g,"p6",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(b5.equals("0") && bb5==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p5='"+sub[f]+" "+user[k]+"' where Day='"+g2+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;bb5=1;
                                    troution(g2,user[k],sub[f],room[kk],5);
                                    semister(sub[f],g2,"p5",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(b6.equals("0") && bb6==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p6='"+sub[f]+" "+user[k]+"' where Day='"+g2+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;bb6=1;
                                    troution(g2,user[k],sub[f],room[kk],6);
                                    semister(sub[f],g2,"p6",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(c5.equals("0") && cc5==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p5='"+sub[f]+" "+user[k]+"' where Day='"+g3+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;cc5=1;
                                    troution(g3,user[k],sub[f],room[kk],5);
                                    semister(sub[f],g3,"p5",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(c6.equals("0") && cc6==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p6='"+sub[f]+" "+user[k]+"' where Day='"+g3+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;cc6=1;
                                    troution(g3,user[k],sub[f],room[kk],6);
                                    semister(sub[f],g3,"p6",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(d5.equals("0") && dd5==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p5='"+sub[f]+" "+user[k]+"' where Day='"+g4+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;dd5=1;
                                    troution(g4,user[k],sub[f],room[kk],5);
                                    semister(sub[f],g4,"p5",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(d6.equals("0") && dd6==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p6='"+sub[f]+" "+user[k]+"' where Day='"+g4+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;dd6=1;
                                    troution(g4,user[k],sub[f],room[kk],6);
                                    semister(sub[f],g4,"p6",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(e5.equals("0") && ee5==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p5='"+sub[f]+" "+user[k]+"' where Day='"+g5+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;ee5=1;
                                    troution(g5,user[k],sub[f],room[kk],5);
                                    semister(sub[f],g5,"p5",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(e6.equals("0") && ee6==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p6='"+sub[f]+" "+user[k]+"' where Day='"+g5+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;ee6=1;
                                    troution(g5,user[k],sub[f],room[kk],6);
                                    semister(sub[f],g5,"p6",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(a1.equals("0") && aa1==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p1='"+sub[f]+" "+user[k]+"' where Day='"+g+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;aa1=1;
                                    troution(g,user[k],sub[f],room[kk],1);
                                    semister(sub[f],g,"p1",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(a2.equals("0") && aa2==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p2='"+sub[f]+" "+user[k]+"' where Day='"+g+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;aa2=1;
                                    troution(g,user[k],sub[f],room[kk],2);
                                    semister(sub[f],g,"p2",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(b1.equals("0") && bb1==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p1='"+sub[f]+" "+user[k]+"' where Day='"+g2+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;bb1=1;
                                    troution(g2,user[k],sub[f],room[kk],1);
                                    semister(sub[f],g2,"p1",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(b2.equals("0") && bb2==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p2='"+sub[f]+" "+user[k]+"' where Day='"+g2+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;bb2=1;
                                    troution(g2,user[k],sub[f],room[kk],2);
                                    semister(sub[f],g2,"p2",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(c1.equals("0") && cc1==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p1='"+sub[f]+" "+user[k]+"' where Day='"+g3+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;cc1=1;
                                    troution(g3,user[k],sub[f],room[kk],1);
                                    semister(sub[f],g3,"p1",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(c2.equals("0") && cc2==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p2='"+sub[f]+" "+user[k]+"' where Day='"+g3+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;cc2=1;
                                    troution(g3,user[k],sub[f],room[kk],2);
                                    semister(sub[f],g3,"p2",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(d1.equals("0") && dd1==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p1='"+sub[f]+" "+user[k]+"' where Day='"+g4+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;dd1=1;
                                    troution(g4,user[k],sub[f],room[kk],1);
                                    semister(sub[f],g4,"p1",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(d2.equals("0") && dd2==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p2='"+sub[f]+" "+user[k]+"' where Day='"+g4+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;dd2=1;
                                    troution(g4,user[k],sub[f],room[kk],2);
                                    semister(sub[f],g4,"p2",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(e1.equals("0") && ee1==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p1='"+sub[f]+" "+user[k]+"' where Day='"+g5+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;ee1=1;
                                    troution(g5,user[k],sub[f],room[kk],1);
                                    semister(sub[f],g5,"p1",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }else if(e2.equals("0") && ee2==0){
                                try{
                                    sq="Update '"+room[kk]+"' set p2='"+sub[f]+" "+user[k]+"' where Day='"+g5+"'";
                                    ps=conn.prepareStatement(sq);
                                    ps.execute();
                                    y=1;ee2=1;
                                    troution(g5,user[k],sub[f],room[kk],2);
                                    semister(sub[f],g5,"p2",room[kk],user[k]);
                                }catch(Exception e){
                                    System.out.println("sub insert problem");
                                }
                                
                            }
                        }
                    }
            }
            
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        //new Main(conn).setVisible(true);
        Main m=new Main(conn);
        m.details(A1,A2);
        m.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void combo_RoomlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_RoomlistActionPerformed
        update_table1();
    }//GEN-LAST:event_combo_RoomlistActionPerformed

    private void comboTecherlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTecherlistActionPerformed
        update_table2();
    }//GEN-LAST:event_comboTecherlistActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        
        String room[]=new String[100];
        String user[]=new String[100];
        String semi[]=new String[10];
        semi[0]="1-1";
        semi[1]="1-2";
        semi[2]="2-1";
        semi[3]="2-2";
        semi[4]="3-1";
        semi[5]="3-2";
        semi[6]="4-1";
        semi[7]="4-2";
        int i=-1,j=-1;
        
        /*room taken condition*/
        try {
            String sql = "select * from roomlist";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
           while(rs.next())
           {
               i++;
              room[i]=rs.getString("roomno");
                
            }
        } catch (SQLException ex) {
            System.out.println("room get problem");
        }finally{
            try {
                ps.close();
                rs.close();
            } catch (SQLException ex) {
                
                //succesMessage.setText("Closing problem");
            }
        }
        
        /*user taken condition*/
        try {
            String sql = "select * from subchoice";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
           while(rs.next())
           {
               j++;
              user[j]=rs.getString("usename");
                
            }
        } catch (SQLException ex) {
            System.out.println("user get problem");
        }finally{
            try {
                ps.close();
                rs.close();
            } catch (SQLException ex) {
                
                //succesMessage.setText("Closing problem");
            }
        }
        
        /*room table delete condition*/
        for(int k=0;k<=i;k++){
            try{
                String sql="delete from '"+room[k]+"'";
                
                ps=conn.prepareStatement(sql);
                ps.executeUpdate();
            }catch(Exception e){
                System.out.println("room table delete problem");
            }
            for(int l=1;l<=5;l++){
                try{
                String sql =new String();
                sql="Insert into '"+room[k]+"' (Day,p1,p2,p3,p4,p5,p6) values (?,?,?,?,?,?,?)";

                ps=conn.prepareStatement(sql);
                if(l==1){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (sunday,0,0,0,0,0,0)";
                    ps.setString(1, "sunday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }else if(l==2){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (monday,0,0,0,0,0,0)";
                    ps.setString(1, "monday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }else if(l==3){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (tuesday,0,0,0,0,0,0)";
                    ps.setString(1, "tuesday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }else if(l==4){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (wednesday,0,0,0,0,0,0)";
                    ps.setString(1, "wednesday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }else if(l==5){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (thusday,0,0,0,0,0,0)";
                    ps.setString(1, "thusday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }
                
                ps.execute();
                //jPanel2.setBackground(new java.awt.Color(0,102,51));
                //Succes.setText("All succesfully add");


            }catch(Exception e){
                //jPanel2.setBackground(new java.awt.Color(255, 0, 0));
                //Succes.setText("value  adding Problem try Again");
                    System.out.println("room value insert problem");
            }
            } 
        }
        
        /*user table delete condition*/
        for(int k=0;k<=j;k++){
            try{

                String sql="delete from '"+user[k]+"'";
                
                ps=conn.prepareStatement(sql);
                ps.executeUpdate();
            }catch(Exception e){
                System.out.println("user table delete problem");
            }
            
            for(int l=1;l<=5;l++){
                try{
                    
                String sql =new String();
                sql="Insert into '"+user[k]+"' (Day,p1,p2,p3,p4,p5,p6) values (?,?,?,?,?,?,?)";

                ps=conn.prepareStatement(sql);
                if(l==1){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (sunday,0,0,0,0,0,0)";
                    ps.setString(1, "sunday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }else if(l==2){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (monday,0,0,0,0,0,0)";
                    ps.setString(1, "monday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }else if(l==3){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (tuesday,0,0,0,0,0,0)";
                    ps.setString(1, "tuesday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }else if(l==4){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (wednesday,0,0,0,0,0,0)";
                    ps.setString(1, "wednesday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }else if(l==5){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (thusday,0,0,0,0,0,0)";
                    ps.setString(1, "thusday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }
                
                ps.execute();
                //jPanel2.setBackground(new java.awt.Color(0,102,51));
                //Succes.setText("All succesfully add");


            }catch(Exception e){
                //jPanel2.setBackground(new java.awt.Color(255, 0, 0));
                //Succes.setText("value  adding Problem try Again");
                    System.out.println("room value insert problem");
            }
            } 
        }
        for(int k=0;k<=7;k++){
            try{

                String sql="delete from '"+semi[k]+"'";
                
                ps=conn.prepareStatement(sql);
                ps.executeUpdate();
            }catch(Exception e){
                System.out.println("user table delete problem");
            }
            
            for(int l=1;l<=5;l++){
                try{
                    
                String sql =new String();
                sql="Insert into '"+semi[k]+"' (Day,p1,p2,p3,p4,p5,p6) values (?,?,?,?,?,?,?)";

                ps=conn.prepareStatement(sql);
                if(l==1){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (sunday,0,0,0,0,0,0)";
                    ps.setString(1, "sunday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }else if(l==2){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (monday,0,0,0,0,0,0)";
                    ps.setString(1, "monday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }else if(l==3){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (tuesday,0,0,0,0,0,0)";
                    ps.setString(1, "tuesday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }else if(l==4){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (wednesday,0,0,0,0,0,0)";
                    ps.setString(1, "wednesday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }else if(l==5){
                    //sql="Insert into '"+us+"' (Day,p1,p2,p3,p4,p5,p6) values (thusday,0,0,0,0,0,0)";
                    ps.setString(1, "thusday");
                    ps.setString(2, "0");
                    ps.setString(3, "0");
                    ps.setString(4, "0");
                    ps.setString(5, "0");
                    ps.setString(6, "0");
                    ps.setString(7, "0");
                }
                
                ps.execute();
                //jPanel2.setBackground(new java.awt.Color(0,102,51));
                //Succes.setText("All succesfully add");


            }catch(Exception e){
                //jPanel2.setBackground(new java.awt.Color(255, 0, 0));
                //Succes.setText("value  adding Problem try Again");
                    System.out.println("room value insert problem");
            }
            }
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try{
            //boolean print=show.print();
            boolean print=jTable1.print();
            if(print){
                System.out.println("Succes");
            }
        }catch(Exception e){
            System.out.println("Fail print");
        } 
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        update_table3();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void semister(String sub,String day,String period,String room,String teacher){
        String semister=new String();
        int i1=0;
        try{
            String sql="select * from subjectList";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next()){
                if(rs.getString("subcode").equals(sub)){
                    semister=rs.getString("semister");
                    i1=1;
                }
            }
        }catch(Exception e){
            System.out.println("semister get problem");
        }finally{
            try {
                rs.close();
                ps.close();
            } catch (SQLException ex) {
                //jPanel2.setBackground(new java.awt.Color(255, 0, 0));
                //Succes.setText("Data closing Problem try Again");
            }
        }
        if(i1==1){
            try{
                String sql="update '"+semister+"' set '"+period+"'=? where Day='"+day+"'";
                ps=conn.prepareStatement(sql);
                ps.setString(1,sub+" Room:"+room+" "+teacher);
                ps.executeUpdate();
            }catch(Exception e){
                System.out.println("semister routin update problem");
            }finally{
            try {
                rs.close();
                ps.close();
            } catch (SQLException ex) {
                //jPanel2.setBackground(new java.awt.Color(255, 0, 0));
                //Succes.setText("Data closing Problem try Again");
            }
        }
        }
    }
    private void troution(String d,String u,String s,String r,int p){
        String sql=new String();
        if(p==1){
            try{
                sql="Update '"+u+"' set p1='"+s+" Room: "+r+"' where Day='"+d+"'";
                ps=conn.prepareStatement(sql);
                ps.execute();
            }catch(Exception e){
                System.out.println("techer routin update problem problem");
            }
        }else if(p==2){
            try{
                sql="Update '"+u+"' set p2='"+s+" Room: "+r+"' where Day='"+d+"'";
                ps=conn.prepareStatement(sql);
                ps.execute();
            }catch(Exception e){
                System.out.println("techer routin update problem problem");
            }
        }if(p==3){
            try{
                sql="Update '"+u+"' set p3='"+s+" Room: "+r+"' where Day='"+d+"'";
                ps=conn.prepareStatement(sql);
                ps.execute();
            }catch(Exception e){
                System.out.println("techer routin update problem problem");
            }
        }if(p==4){
            try{
                sql="Update '"+u+"' set p4='"+s+" Room: "+r+"' where Day='"+d+"'";
                ps=conn.prepareStatement(sql);
                ps.execute();
            }catch(Exception e){
                System.out.println("techer routin update problem problem");
            }
        }if(p==5){
            try{
                sql="Update '"+u+"' set p5='"+s+" Room: "+r+"' where Day='"+d+"'";
                ps=conn.prepareStatement(sql);
                ps.execute();
            }catch(Exception e){
                System.out.println("techer routin update problem problem");
            }
        }if(p==6){
            try{
                sql="Update '"+u+"' set p6='"+s+" Room: "+r+"' where Day='"+d+"'";
                ps=conn.prepareStatement(sql);
                ps.execute();
            }catch(Exception e){
                System.out.println("techer routin update problem problem");
            }finally{
            try {
                rs.close();
                ps.close();
            } catch (SQLException ex) {
                //jPanel2.setBackground(new java.awt.Color(255, 0, 0));
                //Succes.setText("Data closing Problem try Again");
            }
        }
        }
        
    }
    private void list1(){
         String sql = "select * from roomlist";
        try {
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
           while(rs.next())
           {
               String val=rs.getString("roomno");
                combo_Roomlist.addItem(val);
                
            }
           //subList.setModel(getString(rs));
        } catch (SQLException ex) {
            
        }
        String sq = "select * from techertb";
        try {
            ps=conn.prepareStatement(sq);
            rs=ps.executeQuery();
           while(rs.next())
           {
               String val=rs.getString("usename");
                comboTecherlist.addItem(val);
                
            }
           //subList.setModel(getString(rs));
        } catch (Exception ex) {
            
        }
        finally{  
            try {
                rs.close();
                ps.close();
            } catch (SQLException ex) {
                        
            }
          }
    }
    private void update_table1(){
        //table update
        String u= new String();
        String s1=combo_Roomlist.getSelectedItem().toString();
        try {
                u = "select * from '"+s1+"'";
                show.setText("Room : "+s1+" Routin");
                ps=conn.prepareStatement(u);
                rs=ps.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                
          } catch (SQLException ex) {
              System.out.println("roomTable problem");
          }
        finally{
            try {
                rs.close();
                ps.close();
            } catch (SQLException ex) {
                //jPanel2.setBackground(new java.awt.Color(255, 0, 0));
                //Succes.setText("Data closing Problem try Again");
            }
        }
    }
    private void update_table2(){
        //table update
        String u= new String();
        String s2=comboTecherlist.getSelectedItem().toString();
        try {
                u = "select * from '"+s2+"'";
                ps=conn.prepareStatement(u);
                show.setText("Teacher : "+s2+" Routin");
                rs=ps.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                
          } catch (SQLException ex) {
              System.out.println("teacherTable problem");
          }
        finally{
            try {
                rs.close();
                ps.close();
            } catch (SQLException ex) {
                //jPanel2.setBackground(new java.awt.Color(255, 0, 0));
                //Succes.setText("Data closing Problem try Again");
            }
        }
    }
    private void update_table3(){
        //table update
        String u= new String();
        String s2=jComboBox1.getSelectedItem().toString();
        try {
                u = "select * from '"+s2+"'";
                ps=conn.prepareStatement(u);
                show.setText("Semister : "+s2+" Routin");
                rs=ps.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                
          } catch (SQLException ex) {
              System.out.println("semisterTable problem");
          }
        finally{
            try {
                rs.close();
                ps.close();
            } catch (SQLException ex) {
                //jPanel2.setBackground(new java.awt.Color(255, 0, 0));
                //Succes.setText("Data closing Problem try Again");
            }
        }
    }
    void get(String p,String q){
        A1=p;
        A2=q;
    }
    String A1=new String();
    String A2=new String();
    PreparedStatement ps=null;
    ResultSet rs=null;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoutineFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoutineFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoutineFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoutineFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new RoutineFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> comboTecherlist;
    private javax.swing.JComboBox<String> combo_Roomlist;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel show;
    // End of variables declaration//GEN-END:variables
}
